export function TermsOfService() {
    return (
        <div className="min-h-screen bg-neutral-50 dark:bg-neutral-950 text-neutral-900 dark:text-neutral-100 py-20 px-4 transition-colors duration-300">
            <div className="max-w-3xl mx-auto space-y-12">
                <div className="space-y-4 border-b border-neutral-200 dark:border-neutral-800 pb-8">
                    <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Terms of Service</h1>
                    <p className="text-neutral-500 dark:text-neutral-400">Effective from: March 1, 2026</p>
                </div>

                <div className="prose dark:prose-invert max-w-none text-neutral-700 dark:text-neutral-300">
                    <p>
                        Welcome to CodeHeal. These Terms of Service ("Terms") govern your use of our autonomous CI/CD agents and related services. By accessing or using CodeHeal, you agree to these Terms. If you disagree with any part, you must not use our service.
                    </p>

                    <h2>1. Service Provisioning</h2>
                    <p>
                        CodeHeal provides an automated service for modifying source code. While we use advanced AI models verified by multi-stage reasoning pipelines, CodeHeal does not guarantee that every code modification will be bug-free or optimal. <strong>You remain fully responsible for reviewing and approving all pull requests generated by CodeHeal prior to merging them into your production branches.</strong>
                    </p>

                    <h2>2. User Obligations</h2>
                    <p>
                        You agree not to use CodeHeal to:
                    </p>
                    <ul>
                        <li>Scan or modify repositories you do not have explicitly authorized access to.</li>
                        <li>Intentionally inject malicious code or perform denial-of-service attacks on our infrastructure.</li>
                        <li>Resell or redistribute access to the CodeHeal API without an explicit enterprise partnership agreement.</li>
                    </ul>

                    <h2>3. Intellectual Property</h2>
                    <p>
                        You retain all rights, title, and interest in your respective source code. CodeHeal claims absolutely no ownership over the code you submit for analysis, nor the code fixes we generate on your behalf.
                    </p>

                    <h2>4. Limitation of Liability</h2>
                    <p>
                        To the maximum extent permitted by applicable law, CodeHeal, its founders, and employees shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses resulting from your deployment of AI-generated code.
                    </p>
                </div>
            </div>
        </div>
    );
}
